meta:
  engine: 4.1.0
  version: 0.0.1
  author: Henri Nurmi
units:
  $default_width: cx-1
  $default_height: cy-1
  $default_spread: cx
  $default_padding: cy
  kx: cx
  ky: cy
  px: kx + 2
  py: ky + 2
  index_stagger: -4.5
  arch_top_x: 0
  arch_top_y: -65
  arch_top_radius: 110
  arch_bottom_x: -60
  arch_bottom_y: -323
  arch_bottom_radius: 300
  arch_left_x: 290
  arch_left_y: 0
  arch_left_radius: 302
  arch_right_x: -230
  arch_right_y: 20
  arch_right_radius: 300
  mcu_shift_x: kx + 2
  mcu_shift_y: -13.5
  conn_cut_width: 18
  conn_cut_shift_y: 9.6
  mounting_spacer_diameter: 3.1
  mounting_hole_diameter: 2.2
  trrs_shift_x: kx + 17
  trrs_shift_y: mcu_shift_y - 22.5
  reset_shift_x: kx + 13.6
  reset_shfit_y: trrs_shift_y - 6.5
  tenting_puck_shift_y: -ky/2 - 5.6
  logo_shift_y: -16.25
points:
  zones:
    matrix:
      key.tags: switch
      columns:
        pinky:
          rows:
            bottom:
              key_net: P6
            home:
              key_net: P5
            top:
              key_net: P4
        ring:
          key.stagger: 9
          rows:
            bottom:
              key_net: P3
            home:
              key_net: P2
            top:
              key_net: P0
        middle:
          key.stagger: 2.5
          rows:
            bottom:
              key_net: P1
            home:
              key_net: P18
            top:
              key_net: P15
        index:
          key.stagger: index_stagger
          rows:
            bottom:
              key_net: P14
            home:
              key_net: P16
            top:
              key_net: P10
        inner:
          key.stagger: -3.5
          rows:
            bottom:
              key_net: P19
            home:
              key_net: P20
            top:
              key_net: P21
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [50, -100]
    thumbs:
      key.tags: switch
      anchor:
        ref: matrix_index_bottom
        shift: [5, -ky - 3]
        rotate: -5
      columns:
        inner:
          key:
            key_net: P7
        home:
          key:
            shift: [1.1, -5]
            rotate: -10
            key_net: P8
        outer:
          key:
            rotate: 67
            shift: [1, -14]
            key_net: P9
      rows:
        cluster:
    mounting_left:
      key:
        width: 2
        height: 2
        tags: mount
        padding: 2ky
      anchor:
        ref: matrix_pinky_bottom
        shift: [kx/2, ky/2]
      columns:
        c1:
      rows:
        r1:
        r2:
    mounting_right:
      key:
        width: 2
        height: 2
        tags: mount
        padding: 3ky + 1
      anchor:
        ref: matrix_inner_bottom
        shift: [-kx/2 + 1, -ky/2 - 1]
      columns:
        c1:
      rows:
        r1:
        r2:
    mounting_thumb:
      key:
        width: 2
        height: 2
        tags: mount
      anchor:
        ref: thumbs_outer_cluster
        shift: [kx/2 + 2, ky/2 - 2]
      columns:
        c1:
      rows:
        r1:
  mirror:
    ref: matrix_middle_bottom
    distance: 10U
outlines:
  keys:
    - what: rectangle
      where: [switch]
      size: [kx-1, ky-1]
  _top_arch_circle_left:
    - what: circle
      radius: 95
      where:
        ref:
          aggregate.parts:
            - ref: matrix_pinky_top
              orient: 0
              shift: [-kx/2, ky/2]
            - ref: matrix_inner_top
              orient: 0
              shift: [kx/2, ky/2]
          orient:
            ref: matrix_pinky_top
            shift: [-kx/2, ky/2]
        orient: 90
        shift: [0, 83]
  _bottom_arch_circle_left:
    - what: circle
      radius: arch_bottom_radius
      where:
        ref:
          aggregate.parts:
            - matrix_pinky_bottom
            - thumbs_outer_cluster
          orient: matrix_pinky_bottom
        orient: 90
        shift: [0, 308]
  _left_arch_circle_left:
    - what: circle
      radius: arch_left_radius
      where:
        ref: matrix_pinky_home
        shift: [arch_left_x, arch_left_y]
  _right_arch_circle_left:
    - what: circle
      radius: arch_right_radius
      where:
        ref: matrix_middle_bottom
        shift: [arch_right_x, arch_right_y]
  _conn_cut_left:
    - what: rectangle
      size: [conn_cut_width, 10]
      where:
        ref: matrix_inner_top
        shift: [kx + 2, conn_cut_shift_y]
  _arches_left:
    [
      +_top_arch_circle_left,
      -_bottom_arch_circle_left,
      ~_left_arch_circle_left,
      ~_right_arch_circle_left,
    ]
  # Outline arches for right side
  _top_arch_circle_right:
    - what: circle
      radius: arch_top_radius
      where:
        ref: mirror_matrix_middle_bottom
        shift: [arch_top_x, arch_top_y]
  _bottom_arch_circle_right:
    - what: circle
      radius: arch_bottom_radius
      where:
        ref: mirror_matrix_middle_bottom
        shift: [arch_bottom_x, arch_bottom_y]
  _left_arch_circle_right:
    - what: circle
      radius: arch_left_radius
      where:
        ref: mirror_matrix_pinky_home
        shift: [arch_left_x, arch_left_y]
  _right_arch_circle_right:
    - what: circle
      radius: arch_right_radius
      where:
        ref: mirror_matrix_middle_bottom
        shift: [arch_right_x, arch_right_y]
  _conn_cut_right:
    - what: rectangle
      size: [conn_cut_width, 10]
      where:
        ref: mirror_matrix_inner_top
        shift: [kx + 2, conn_cut_shift_y]
  _arches_right:
    [
      +_top_arch_circle_right,
      -_bottom_arch_circle_right,
      ~_left_arch_circle_right,
      ~_right_arch_circle_right,
    ]
  # Mounting holes
  _mounting_holes:
    - what: circle
      radius: mounting_hole_diameter/2
      where: mount
  # Tenting Puck
  _tenting_puck:
    - what: circle
      radius: 41.5/2
      where:
        ref: matrix_middle_home
        shift: [kx/2, tenting_puck_shift_y]
  # Board outlines
  board_outline_left:
    - what: outline
      name: _arches_left
      fillet: 3
  board_outline_right:
    - what: outline
      name: _arches_right
      fillet: 3
  board_left:
    [ board_outline_left, -_mounting_holes]
  board_right:
    [ board_outline_right, -_mounting_holes]
  board_pcb_left:
    [ board_outline_left, -_conn_cut_left]
  board_pcb_right:
    [ board_outline_right, -_conn_cut_right]
  board_tenting_puck_left:
    [ board_outline_left, -_tenting_puck]
  # Switch plate
  _switch_cutouts:
    - what: rectangle
      where: [switch]
      asym: source
      size: 14
      bound: false
  _mcu_cutout:
    - what: rectangle
      size: [30, 60]
      where:
        ref: matrix_inner_home
        shift: [0.5kx + 30/2 + 0.5, -0.5ky + 60/2 + 0.5]
  switch_plate:
    [board_outline_left, -_switch_cutouts, -_mcu_cutout]
  switch_plate_with_mouting:
    [switch_plate, -_mounting_holes]
  # Debug outlines
  _debug:
    - name: board_left
    - operation: stack
      name: keys
  debug:
    - name: _mounting_holes
    - operation: stack
      name: _debug
pcbs:
  left:
    template: kicad8
    outlines:
      main:
        outline: board_pcb_left
    footprints:
      switch:
        what: choc
        where: [[-/^mirror_.*/, switch]]
        adjust:
          rotate: 180
        params:
          from: "{{key_net}}"
          to: GND
          hotswap: true
          keycaps: true
      promicro:
        what: promicro_custom
        where:
          ref: matrix_inner_top
          shift: [mcu_shift_x, mcu_shift_y]
          rotate: -90
        params:
          orientation: down
      trrs:
        what: trrs
        where:
          ref: matrix_inner_top
          shift: [trrs_shift_x, trrs_shift_y]
          rotate: -90
        params:
          A: VCC
          B: DATA
          C: GND
          D: ''
      reset:
        what: reset_button
        where:
          ref: matrix_inner_top
          shift: [reset_shift_x, reset_shfit_y]
          rotate: -90
      zone_front:
        what: zone
        where:
          ref: matrix_pinky_top
          shift: [-1kx, 1.2ky]
        params:
          net: VCC
          side: F
          width: 8.5kx
          height: 6.5ky
      zone_back:
        what: zone
        where:
          ref: matrix_pinky_top
          shift: [-1kx, 1.2ky]
        params:
          net: GND
          side: B
          width: 8.5kx
          height: 6.5ky
      mounting:
        what: mounting_hole_plated
        where: [[-/^mirror_.*/, mount]]
        params.drill: mounting_spacer_diameter
      text_left:
        what: text
        where:
          ref: matrix_inner_top
          shift: [mcu_shift_x, mcu_shift_y]
        params:
          text: "Left\\nUp"
      text_version:
        what: version
        where:
          ref: matrix_inner_top
          shift: [mcu_shift_x, mcu_shift_y + 16.5]
      tenting_puck:
        what: tenting_puck
        where:
          ref: matrix_middle_home
          shift: [kx/2, tenting_puck_shift_y]
      logo:
        what: logo
        where:
          ref: matrix_ring_bottom
          shift: [0, logo_shift_y]
  right:
    template: kicad8
    outlines:
      main:
        outline: board_pcb_right
    footprints:
      switch:
        what: choc
        where: [[/^mirror_.*/, switch]]
        adjust:
          rotate: 180
        params:
          from: "{{key_net}}"
          to: GND
          hotswap: true
          keycaps: true
      promicro:
        what: promicro_custom
        where:
          ref: mirror_matrix_inner_top
          shift: [mcu_shift_x, mcu_shift_y]
          rotate: 90
        params:
          orientation: down
      trrs:
        what: trrs
        where:
          ref: mirror_matrix_inner_top
          shift: [trrs_shift_x, trrs_shift_y + 4.6]
          rotate: -90
        params:
          A: VCC
          B: DATA
          C: GND
          D: ''
      reset:
        what: reset_button
        where:
          ref: mirror_matrix_inner_top
          shift: [reset_shift_x, reset_shfit_y]
          rotate: -90
      zone_front:
        what: zone
        where:
          ref: mirror_matrix_pinky_top
          shift: [-1kx, 1.2ky]
        params:
          net: VCC
          side: F
          width: -8.5kx
          height: 6.5ky
      zone_back:
        what: zone
        where:
          ref: mirror_matrix_pinky_top
          shift: [-1kx, 1.2ky]
        params:
          net: GND
          side: B
          width: -8.5kx
          height: 6.5ky
      mounting:
        what: mounting_hole_plated
        where: [[/^mirror_.*/, mount]]
        params.drill: mounting_spacer_diameter
      text_right:
        what: text
        where:
          ref: mirror_matrix_inner_top
          shift: [mcu_shift_x, mcu_shift_y]
        params:
          text: "Right\\nUp"
      text_version:
        what: version
        where:
          ref: mirror_matrix_inner_top
          shift: [mcu_shift_x, mcu_shift_y + 16.5]
      tenting_puck:
        what: tenting_puck
        where:
          ref: mirror_matrix_middle_home
          shift: [kx/2, tenting_puck_shift_y]
      logo:
        what: logo
        where:
          ref: mirror_matrix_ring_bottom
          shift: [0, logo_shift_y]
  switch_plate:
    template: kicad8
    outlines:
      main:
        outline: switch_plate
    footprints:
      mounting:
        what: mounting_hole_npth
        where: [[-/^mirror_.*/, mount]]
        params.hole_size: mounting_hole_diameter
        params.hole_drill: mounting_hole_diameter
      text_version_front:
        what: version
        where:
          ref: matrix_pinky_top
          shift: [kx/2, -ky/2]
          rotate: 90
        params:
          layer: Cu
          side: F
      text_version_back:
        what: version
        where:
          ref: matrix_pinky_top
          shift: [kx/2, -ky/2]
          rotate: 90
        params:
          layer: Cu
          side: B
          mirrored: true
      zone_front:
        what: zone
        where:
          ref: matrix_pinky_top
          shift: [-1kx, 1.2ky]
        params:
          net: ''
          side: F
          width: 8.5kx
          height: 6.5ky
      zone_back:
        what: zone
        where:
          ref: matrix_pinky_top
          shift: [-1kx, 1.2ky]
        params:
          net: ''
          side: B
          width: 8.5kx
          height: 6.5ky
  bottom_board_with_art:
    template: kicad8
    outlines:
      main:
        outline: board_outline_left
    footprints:
      mounting:
        what: mounting_hole_npth
        where: [[-/^mirror_.*/, mount]]
        params.hole_size: mounting_hole_diameter
        params.hole_drill: mounting_hole_diameter
      art:
        what: artwork
  bottom_board_with_tenting_puck:
    template: kicad8
    outlines:
      main:
        outline: board_tenting_puck_left
    footprints: &bottom_footprints
      mounting:
        what: mounting_hole_npth
        where: [[-/^mirror_.*/, mount]]
        params.hole_size: mounting_hole_diameter
        params.hole_drill: mounting_hole_diameter
      logo_front:
        what: logo
        where:
          ref: matrix_middle_top
          shift: [kx/2, -ky/2]
      logo_back:
        what: logo
        where:
          ref: matrix_middle_top
          shift: [kx/2, -ky/2]
        params:
          mirrored: true
      text_version_front:
        what: version
        where:
          ref: matrix_pinky_top
          shift: [kx/2, -ky/2]
          rotate: 90
        params:
          layer: Cu
          side: F
      text_version_back:
        what: version
        where:
          ref: matrix_pinky_top
          shift: [kx/2, -ky/2]
          rotate: 90
        params:
          layer: Cu
          side: B
          mirrored: true
      zone_front:
        what: zone
        where:
          ref: matrix_pinky_top
          shift: [-1kx, 1.2ky]
        params:
          net: ''
          side: F
          width: 8.5kx
          height: 6.5ky
      zone_back:
        what: zone
        where:
          ref: matrix_pinky_top
          shift: [-1kx, 1.2ky]
        params:
          net: ''
          side: B
          width: 8.5kx
          height: 6.5ky
  bottom_board_empty:
    template: kicad8
    outlines:
      main:
        outline: board_outline_left
    footprints: *bottom_footprints
